In [1]:
3+2

5

## LS-Magic

In [2]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

 ## Numpy

In [3]:
import numpy as np

In [4]:
arr = np.array([2,3,4,5])
print(arr)

[2 3 4 5]


In [5]:
arr*arr

array([ 4,  9, 16, 25])

In [6]:
1/arr

array([0.5       , 0.33333333, 0.25      , 0.2       ])

In [7]:
arr.dtype

dtype('int32')

In [8]:
arr.shape

(4,)

In [9]:
arr1 = np.array([[2,3,4,5],
                [3,4,5,6]])
print(arr1)

[[2 3 4 5]
 [3 4 5 6]]


In [10]:
arr1.shape

(2, 4)

In [11]:
arr2= np.zeros((2,4))
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
%time arr2

Wall time: 0 ns


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
%timeit arr

49.7 ns ± 5.83 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [14]:
np.ones((2,1))

array([[1.],
       [1.]])

In [15]:
np.array([2,1])

array([2, 1])

## Maths

In [16]:
import math as m

In [17]:
m.factorial(0)

1

In [18]:
m.log2(4)

2.0

In [19]:
m.log2(16)

4.0

In [20]:
m.pow(2,5)

32.0

In [21]:
m.cos(20)

0.40808206181339196

In [22]:
m.tan(45)

1.6197751905438615

In [23]:
m.sin(30)

-0.9880316240928618

In [24]:
m.e

2.718281828459045

In [25]:
m.pi

3.141592653589793

In [26]:
m.sqrt(81)

9.0

In [27]:
time m.sqrt(64)

Wall time: 0 ns


8.0

In [28]:
%timeit m.sqrt(64)

309 ns ± 41.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [29]:
var_1 = 10

In [30]:
var_2 = 'Hansil'

In [31]:
var_3 = "89"

In [32]:
%who str

var_2	 var_3	 


In [33]:
%who int

var_1	 


In [34]:
%who int

var_1	 


In [35]:
%pinfo var_1

In [36]:
2+3

5

In [37]:
%%html 
<h1>HTML</h1>

In [38]:
%%html
<font size=6 color='REd'>Hello World</font>

In [39]:
import numpy as np

In [40]:
a = np.array([1,4,7])

In [41]:
b = np.array([2,9,5])

In [42]:
np.dot(a,b.transpose())

73

In [43]:
np.cross(a,b.transpose())

array([-43,   9,   1])

In [44]:
ar = np.array(([2,4,0],
               [3,4,1]))

In [45]:
np.sum(ar, axis=1)

array([6, 8])

In [49]:
np.sort(ar,axis=1, kind='quicksort')

array([[0, 2, 4],
       [1, 3, 4]])