In [1]:
import numpy as np

In [2]:
a = np.arange(3)

In [3]:
a

array([0, 1, 2])

In [4]:
np.sort(a)

array([0, 1, 2])

In [5]:
a1 = np.array([1,2,3,4,5,6,7,8,9])

In [6]:
a = a1.reshape(3,3)

In [7]:
np.argsort(a,axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [8]:
np.argmin(a1)

0

In [9]:
np.argmax(a1)

8

In [10]:
a2 = np.array([2,1,14,55,17,8,9,10])

In [11]:
np.sort(a2)

array([ 1,  2,  8,  9, 10, 14, 17, 55])

In [12]:
np.argsort(a2)

array([1, 0, 5, 6, 7, 2, 4, 3], dtype=int64)

In [13]:
a = a2.reshape(8)

In [14]:
a

array([ 2,  1, 14, 55, 17,  8,  9, 10])

In [15]:
np.argsort(a, axis=0)

array([1, 0, 5, 6, 7, 2, 4, 3], dtype=int64)

In [16]:
a3 = np.array([1,12,33,43,4,65,6,87,8])

In [17]:
np.sort(a3)

array([ 1,  4,  6,  8, 12, 33, 43, 65, 87])

In [18]:
b= a3.reshape(9)
b

array([ 1, 12, 33, 43,  4, 65,  6, 87,  8])

In [19]:
np.argsort(b)

array([0, 4, 6, 8, 1, 2, 3, 5, 7], dtype=int64)